import React, { useState, useEffect } from 'react';
import { FiDownload, FiCode, FiArchive } from 'react-icons/fi';
import api from '../../services/api';
import { useNotificationStore } from '../../stores/notificationStore';
import styles from './ExportHistory.module.css';

const ExportHistory = () => {
  const [batches, setBatches] = useState([]);
  const [loading, setLoading] = useState(true);
  const addNotification = useNotificationStore(state => state.addNotification);

  const fetchHistory = async () => {
    try {
      const res = await api.get('/api/accounting/export/history');
      setBatches(res.data);
    } catch (err) {
      addNotification({ type: 'error', message: 'Failed to fetch export history' });
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchHistory();
  }, []);

  const handleDownload = async (batchId, format) => {
    try {
      const res = await api.get(`/api/accounting/export/download/${batchId}?format=${format}`, {
        responseType: 'blob'
      });
      const url = window.URL.createObjectURL(new Blob([res.data]));
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', `Batch_${batchId}_Export.${format}`);
      document.body.appendChild(link);
      link.click();
      link.remove();
    } catch (err) {
      addNotification({ type: 'error', message: 'Failed to download file' });
    }
  };

  return (
    <div className={styles.container}>
      <header className={styles.header}>
        <h1 className={styles.title}>Export History</h1>
      </header>

      <div className={styles.contentWrapper}>
        <div className={styles.tableWrapper}>
          <table className={styles.table}>
            <thead>
              <tr>
                <th>Batch ID</th>
                <th>Type</th>
                <th>Generated At</th>
                <th>Generated By</th>
                <th>Invoices</th>
                <th>Status</th>
                <th style={{ textAlign: 'right' }}>Actions</th>
              </tr>
            </thead>
            <tbody>
              {loading ? (
                <tr><td colSpan="7" style={{ textAlign: 'center', padding: '24px' }}>Loading...</td></tr>
              ) : batches.length === 0 ? (
                <tr><td colSpan="7" style={{ textAlign: 'center', padding: '24px' }}>No history found.</td></tr>
              ) : (
                batches.map(b => (
                  <tr key={b.id}>
                    <td style={{ fontWeight: 600, fontSize: '0.9rem' }}>{b.batch_number || `#${b.id}`}</td>
                    <td>{b.batch_type}</td>
                    <td>{new Date(b.generated_at).toLocaleString()}</td>
                    <td>{b.generated_by}</td>
                    <td>{b.invoice_count}</td>
                    <td>
                      <span className={`${styles.badge} ${styles[b.status.toLowerCase().replace(' ', '')] || ''}`}>
                        {b.status}
                      </span>
                      {b.errors && (
                        <div style={{ fontSize: '0.75rem', color: '#ef4444', marginTop: 4 }}>
                          {b.errors}
                        </div>
                      )}
                    </td>
                    <td>
                      <div className={styles.actionGroup} style={{ justifyContent: 'flex-end' }}>
                        <button 
                          className={`${styles.btnIcon} ${styles.primary}`}
                          title="Download XML"
                          disabled={!b.has_file}
                          onClick={() => handleDownload(b.id, 'xml')}
                        >
                          <FiCode />
                        </button>
                        <button 
                          className={`${styles.btnIcon} ${styles.primary}`}
                          title="Download ZIP (Includes Manifest)"
                          disabled={!b.has_file}
                          onClick={() => handleDownload(b.id, 'zip')}
                        >
                          <FiArchive />
                        </button>
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

export default ExportHistory;
