export const ROUTES = {
  LOGIN: '/login',
  OVERVIEW: '/',
  PRODUCTS: '/products',
  WAREHOUSES: '/warehouses',
  INVENTORY: '/inventory',
  INVENTORY_HISTORY: '/inventory-history',
  REPORTS: '/reports',
  DOWNLOAD_CENTRE: '/download-centre',
  SETTINGS: '/settings',
  POS: '/pos',
  POS_HISTORY: '/pos-history',
  POS_INVOICE: '/sales/:saleId/invoice',
  REPLENISHMENT_JSPL: '/replenishment/jspl',
  REPLENISHMENT_BKR: '/replenishment/bkr',
  REPLENISHMENT_BKR_INVOICE: '/replenishment/bkr/:id',
  INTER_COMPANY_HISTORY: '/replenishment/history',
};
