"""Add idempotency keys

Revision ID: 0a0c9f0357f9
Revises: e5ffc85b7f0d
Create Date: 2026-08-12 13:48:04.609562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a0c9f0357f9'
down_revision: Union[str, Sequence[str], None] = 'e5ffc85b7f0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fc_dispatches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idempotency_key', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_fc_dispatches_idempotency_key'), ['idempotency_key'], unique=False)
        batch_op.create_unique_constraint('uix_company_dispatch_idempotency_key', ['company_id', 'idempotency_key'])

    with op.batch_alter_table('fc_returns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idempotency_key', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_fc_returns_idempotency_key'), ['idempotency_key'], unique=False)
        batch_op.create_unique_constraint('uix_company_fcreturn_idempotency_key', ['company_id', 'idempotency_key'])

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idempotency_key', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_sales_idempotency_key'), ['idempotency_key'], unique=False)
        batch_op.create_unique_constraint('uix_company_sale_idempotency_key', ['company_id', 'idempotency_key'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_constraint('uix_company_sale_idempotency_key', type_='unique')
        batch_op.drop_index(batch_op.f('ix_sales_idempotency_key'))
        batch_op.drop_column('idempotency_key')

    with op.batch_alter_table('fc_returns', schema=None) as batch_op:
        batch_op.drop_constraint('uix_company_fcreturn_idempotency_key', type_='unique')
        batch_op.drop_index(batch_op.f('ix_fc_returns_idempotency_key'))
        batch_op.drop_column('idempotency_key')

    with op.batch_alter_table('fc_dispatches', schema=None) as batch_op:
        batch_op.drop_constraint('uix_company_dispatch_idempotency_key', type_='unique')
        batch_op.drop_index(batch_op.f('ix_fc_dispatches_idempotency_key'))
        batch_op.drop_column('idempotency_key')

    # ### end Alembic commands ###
