"""Add replenishment tables

Revision ID: 35f3c3e90e39
Revises: d1cfeb62ff01
Create Date: 2026-07-31 16:29:08.379760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35f3c3e90e39'
down_revision: Union[str, Sequence[str], None] = 'd1cfeb62ff01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('replenishment_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('run_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('amazon_sync_log_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['amazon_sync_log_id'], ['amazon_sync_logs.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_replenishment_runs_id'), 'replenishment_runs', ['id'], unique=False)
    op.create_table('stock_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transfer_number', sa.String(), nullable=False),
    sa.Column('from_company_id', sa.Integer(), nullable=False),
    sa.Column('to_company_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('dispatch_date', sa.DateTime(), nullable=True),
    sa.Column('received_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('total_value', sa.Float(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['from_company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['sales.id'], ),
    sa.ForeignKeyConstraint(['to_company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_transfers_id'), 'stock_transfers', ['id'], unique=False)
    op.create_index(op.f('ix_stock_transfers_transfer_number'), 'stock_transfers', ['transfer_number'], unique=True)
    op.create_table('replenishment_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('current_stock', sa.Integer(), nullable=True),
    sa.Column('reserved_stock', sa.Integer(), nullable=True),
    sa.Column('available_stock', sa.Integer(), nullable=True),
    sa.Column('today_demand', sa.Integer(), nullable=True),
    sa.Column('safety_stock', sa.Integer(), nullable=True),
    sa.Column('recommended_qty', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['replenishment_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_replenishment_recommendations_id'), 'replenishment_recommendations', ['id'], unique=False)
    op.create_table('stock_transfer_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transfer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('requested_qty', sa.Integer(), nullable=True),
    sa.Column('approved_qty', sa.Integer(), nullable=True),
    sa.Column('dispatched_qty', sa.Integer(), nullable=True),
    sa.Column('received_qty', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('total_value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['transfer_id'], ['stock_transfers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_transfer_items_id'), 'stock_transfer_items', ['id'], unique=False)
    op.add_column('company_settings', sa.Column('replenishment_enabled', sa.Boolean(), nullable=True))
    op.add_column('company_settings', sa.Column('replenishment_time', sa.String(), nullable=True))
    op.add_column('company_settings', sa.Column('replenishment_buffer_minutes', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('reorder_level', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('safety_stock', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('preferred_transfer_qty', sa.Integer(), nullable=True))
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    op.drop_column('products', 'preferred_transfer_qty')
    op.drop_column('products', 'safety_stock')
    op.drop_column('products', 'reorder_level')
    op.drop_column('company_settings', 'replenishment_buffer_minutes')
    op.drop_column('company_settings', 'replenishment_time')
    op.drop_column('company_settings', 'replenishment_enabled')
    op.drop_index(op.f('ix_stock_transfer_items_id'), table_name='stock_transfer_items')
    op.drop_table('stock_transfer_items')
    op.drop_index(op.f('ix_replenishment_recommendations_id'), table_name='replenishment_recommendations')
    op.drop_table('replenishment_recommendations')
    op.drop_index(op.f('ix_stock_transfers_transfer_number'), table_name='stock_transfers')
    op.drop_index(op.f('ix_stock_transfers_id'), table_name='stock_transfers')
    op.drop_table('stock_transfers')
    op.drop_index(op.f('ix_replenishment_runs_id'), table_name='replenishment_runs')
    op.drop_table('replenishment_runs')
    # ### end Alembic commands ###
