"""Add Admin Approval Models

Revision ID: 377c1d491021
Revises: 6b6988e5f36a
Create Date: 2026-08-20 13:14:25.368468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '377c1d491021'
down_revision: Union[str, Sequence[str], None] = '6b6988e5f36a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_approval_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_type', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('related_entity', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('approver_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('admin_comment', sa.String(), nullable=True),
    sa.Column('before_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('revert_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_type', 'idempotency_key', name='uq_request_type_idempotency_key')
    )
    with op.batch_alter_table('admin_approval_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_approval_requests_approver_id'), ['approver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_approval_requests_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_approval_requests_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_approval_requests_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_admin_approval_requests_requested_by'), ['requested_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_approval_requests_status'), ['status'], unique=False)

    op.create_table('admin_approval_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('approval_request_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['approval_request_id'], ['admin_approval_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_approval_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_approval_events_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_approval_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_approval_events_id'))

    op.drop_table('admin_approval_events')
    with op.batch_alter_table('admin_approval_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_approval_requests_status'))
        batch_op.drop_index(batch_op.f('ix_admin_approval_requests_requested_by'))
        batch_op.drop_index(batch_op.f('ix_admin_approval_requests_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_admin_approval_requests_id'))
        batch_op.drop_index(batch_op.f('ix_admin_approval_requests_company_id'))
        batch_op.drop_index(batch_op.f('ix_admin_approval_requests_approver_id'))

    op.drop_table('admin_approval_requests')
    # ### end Alembic commands ###
