"""add operation_id to inventory_movements

Revision ID: 4cbe0350fa81
Revises: bd83021fa1c7
Create Date: 2026-08-09 20:47:30.298174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cbe0350fa81'
down_revision: Union[str, Sequence[str], None] = 'bd83021fa1c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_movements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('operation_id', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_inventory_movements_operation_id'), ['operation_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_movements_operation_id'))
        batch_op.drop_column('operation_id')

    # ### end Alembic commands ###
