"""Add payload_hash and expires_at

Revision ID: 5c544e20180a
Revises: d893ec7e3ff0
Create Date: 2026-08-20 13:47:00.605549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c544e20180a'
down_revision: Union[str, Sequence[str], None] = 'd893ec7e3ff0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_approval_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payload_hash', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_admin_approval_requests_payload_hash'), ['payload_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_approval_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_approval_requests_payload_hash'))
        batch_op.drop_column('expires_at')
        batch_op.drop_column('payload_hash')

    # ### end Alembic commands ###
