"""Add metadata_payload to inventory_movements

Revision ID: 7308742e11ae
Revises: 8de609be852a
Create Date: 2026-07-27 12:22:54.308365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7308742e11ae'
down_revision: Union[str, Sequence[str], None] = '8de609be852a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_movements', sa.Column('metadata_payload', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_movements', 'metadata_payload')
    # ### end Alembic commands ###
