"""Add Amazon Returns Models

Revision ID: 7497b42f0300
Revises: a18c05a1dd3a
Create Date: 2026-08-03 11:20:06.706538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7497b42f0300'
down_revision: Union[str, Sequence[str], None] = 'a18c05a1dd3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amazon_return_sync_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('records_created', sa.Integer(), nullable=True),
    sa.Column('records_updated', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_amazon_return_sync_logs_id'), 'amazon_return_sync_logs', ['id'], unique=False)
    op.create_table('amazon_returns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('amazon_return_id', sa.String(), nullable=False),
    sa.Column('amazon_order_id', sa.String(), nullable=False),
    sa.Column('order_item_id', sa.String(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('asin', sa.String(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('return_reason', sa.String(), nullable=True),
    sa.Column('return_status', sa.String(), nullable=True),
    sa.Column('inspection_status', sa.String(), nullable=True),
    sa.Column('inspection_notes', sa.Text(), nullable=True),
    sa.Column('inspected_by', sa.Integer(), nullable=True),
    sa.Column('inspected_at', sa.DateTime(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['inspected_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'amazon_return_id', 'order_item_id', name='uix_company_return_item')
    )
    op.create_index(op.f('ix_amazon_returns_amazon_order_id'), 'amazon_returns', ['amazon_order_id'], unique=False)
    op.create_index(op.f('ix_amazon_returns_amazon_return_id'), 'amazon_returns', ['amazon_return_id'], unique=False)
    op.create_index(op.f('ix_amazon_returns_id'), 'amazon_returns', ['id'], unique=False)
    op.create_index(op.f('ix_amazon_returns_sku'), 'amazon_returns', ['sku'], unique=False)
    op.add_column('company_settings', sa.Column('amazon_returns_sync_enabled', sa.Boolean(), nullable=True))
    op.add_column('company_settings', sa.Column('amazon_returns_sync_interval_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_company_bill_number', 'sales', type_='unique')
    op.alter_column('inventory', 'available_qty',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('inventory', 'reserved_qty',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('inventory', 'current_qty',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('uix_user_company', 'company_users', type_='unique')
    op.drop_column('company_settings', 'amazon_returns_sync_interval_minutes')
    op.drop_column('company_settings', 'amazon_returns_sync_enabled')
    op.drop_index(op.f('ix_amazon_returns_sku'), table_name='amazon_returns')
    op.drop_index(op.f('ix_amazon_returns_id'), table_name='amazon_returns')
    op.drop_index(op.f('ix_amazon_returns_amazon_return_id'), table_name='amazon_returns')
    op.drop_index(op.f('ix_amazon_returns_amazon_order_id'), table_name='amazon_returns')
    op.drop_table('amazon_returns')
    op.drop_index(op.f('ix_amazon_return_sync_logs_id'), table_name='amazon_return_sync_logs')
    op.drop_table('amazon_return_sync_logs')
    # ### end Alembic commands ###
