"""Add JobExecutionLog

Revision ID: 7638c0224e8a
Revises: 7308742e11ae
Create Date: 2026-07-27 12:40:09.800535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7638c0224e8a'
down_revision: Union[str, Sequence[str], None] = '7308742e11ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_execution_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_execution_logs_id'), 'job_execution_logs', ['id'], unique=False)
    op.create_index(op.f('ix_job_execution_logs_job_name'), 'job_execution_logs', ['job_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_execution_logs_job_name'), table_name='job_execution_logs')
    op.drop_index(op.f('ix_job_execution_logs_id'), table_name='job_execution_logs')
    op.drop_table('job_execution_logs')
    # ### end Alembic commands ###
