"""Add force_reexport_reason to AccountingExportBatch

Revision ID: 76feb95df8f1
Revises: b56b61357c83
Create Date: 2026-08-07 11:02:24.861555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76feb95df8f1'
down_revision: Union[str, Sequence[str], None] = 'b56b61357c83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('acc_export_batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('force_reexport_reason', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('acc_export_batches', schema=None) as batch_op:
        batch_op.drop_column('force_reexport_reason')

    # ### end Alembic commands ###
