"""add_fc_dispatch_payload

Revision ID: 81fd658ad584
Revises: 464da38dadb1
Create Date: 2026-08-20 15:29:19.569490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81fd658ad584'
down_revision: Union[str, Sequence[str], None] = '464da38dadb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fc_dispatches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payload', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fc_dispatches', schema=None) as batch_op:
        batch_op.drop_column('payload')

    # ### end Alembic commands ###
