"""Add accounting integration schema

Revision ID: 851f2e1b41aa
Revises: 35f3c3e90e39
Create Date: 2026-08-01 15:13:48.709032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '851f2e1b41aa'
down_revision: Union[str, Sequence[str], None] = '35f3c3e90e39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acc_configurations',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('default_sales_ledger', sa.String(), nullable=True),
    sa.Column('default_purchase_ledger', sa.String(), nullable=True),
    sa.Column('round_off_ledger', sa.String(), nullable=True),
    sa.Column('discount_ledger', sa.String(), nullable=True),
    sa.Column('freight_ledger', sa.String(), nullable=True),
    sa.Column('default_godown', sa.String(), nullable=True),
    sa.Column('default_voucher_type', sa.String(), nullable=True),
    sa.Column('voucher_series', sa.String(), nullable=True),
    sa.Column('min_tally_version', sa.String(), nullable=True),
    sa.Column('xml_version', sa.String(), nullable=True),
    sa.Column('export_format', sa.String(), nullable=True),
    sa.Column('http_endpoint', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('acc_export_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('batch_type', sa.String(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('generated_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('invoice_count', sa.Integer(), nullable=True),
    sa.Column('errors', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acc_export_batches_id'), 'acc_export_batches', ['id'], unique=False)
    op.create_table('acc_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('mapping_type', sa.String(), nullable=False),
    sa.Column('erp_reference', sa.String(), nullable=False),
    sa.Column('accounting_name', sa.String(), nullable=False),
    sa.Column('aliases', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'mapping_type', 'erp_reference', name='uix_acc_mapping')
    )
    op.create_index(op.f('ix_acc_mappings_id'), 'acc_mappings', ['id'], unique=False)
    op.create_table('acc_master_sync_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('master_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('sync_status', sa.String(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'master_type', 'entity_id', name='uix_master_sync')
    )
    op.create_index(op.f('ix_acc_master_sync_logs_id'), 'acc_master_sync_logs', ['id'], unique=False)
    op.create_table('acc_export_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('last_export_time', sa.DateTime(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('tally_response_status', sa.String(), nullable=True),
    sa.Column('tally_response_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['acc_export_batches.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acc_export_logs_id'), 'acc_export_logs', ['id'], unique=False)
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    op.drop_index(op.f('ix_acc_export_logs_id'), table_name='acc_export_logs')
    op.drop_table('acc_export_logs')
    op.drop_index(op.f('ix_acc_master_sync_logs_id'), table_name='acc_master_sync_logs')
    op.drop_table('acc_master_sync_logs')
    op.drop_index(op.f('ix_acc_mappings_id'), table_name='acc_mappings')
    op.drop_table('acc_mappings')
    op.drop_index(op.f('ix_acc_export_batches_id'), table_name='acc_export_batches')
    op.drop_table('acc_export_batches')
    op.drop_table('acc_configurations')
    # ### end Alembic commands ###
