"""Add Job Card and Service Invoice models

Revision ID: 868ed8b3da70
Revises: 4cbe0350fa81
Create Date: 2026-08-10 15:11:46.015453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '868ed8b3da70'
down_revision: Union[str, Sequence[str], None] = '4cbe0350fa81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('job_card_number', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('machine_type', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('power_type', sa.String(), nullable=True),
    sa.Column('warranty', sa.Boolean(), nullable=True),
    sa.Column('complaint', sa.Text(), nullable=True),
    sa.Column('workshop_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['workshop_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_cards_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_cards_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_cards_job_card_number'), ['job_card_number'], unique=True)

    op.create_table('job_cards_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_card_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('product_sku', sa.String(), nullable=True),
    sa.Column('qty', sa.Float(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['job_card_id'], ['job_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_cards_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_cards_items_id'), ['id'], unique=False)

    op.create_table('service_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(), nullable=False),
    sa.Column('job_card_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('cgst_amount', sa.Float(), nullable=True),
    sa.Column('sgst_amount', sa.Float(), nullable=True),
    sa.Column('grand_total', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['job_card_id'], ['job_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_invoices_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_invoices_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_invoices_invoice_number'), ['invoice_number'], unique=True)

    op.create_table('service_invoice_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('product_sku', sa.String(), nullable=True),
    sa.Column('hsn', sa.String(), nullable=True),
    sa.Column('gst_rate', sa.Float(), nullable=True),
    sa.Column('qty', sa.Float(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['service_invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_invoice_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_invoice_items_id'), ['id'], unique=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('unique_sku_per_company'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('unique_sku_per_company'), ['company_id', 'sku'], unique=1)

    with op.batch_alter_table('service_invoice_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_invoice_items_id'))

    op.drop_table('service_invoice_items')
    with op.batch_alter_table('service_invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_invoices_invoice_number'))
        batch_op.drop_index(batch_op.f('ix_service_invoices_id'))
        batch_op.drop_index(batch_op.f('ix_service_invoices_company_id'))

    op.drop_table('service_invoices')
    with op.batch_alter_table('job_cards_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_cards_items_id'))

    op.drop_table('job_cards_items')
    with op.batch_alter_table('job_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_cards_job_card_number'))
        batch_op.drop_index(batch_op.f('ix_job_cards_id'))
        batch_op.drop_index(batch_op.f('ix_job_cards_company_id'))

    op.drop_table('job_cards')
    # ### end Alembic commands ###
