"""Add warehouse type, external mapping, and dispatch timeline

Revision ID: 8c70a71d0517
Revises: fbc3ad4bccce
Create Date: 2026-08-04 17:37:27.051871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c70a71d0517'
down_revision: Union[str, Sequence[str], None] = 'fbc3ad4bccce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse_external_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('marketplace', sa.String(), nullable=False),
    sa.Column('external_code', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'marketplace', name='uix_warehouse_marketplace')
    )
    op.create_index(op.f('ix_warehouse_external_mappings_external_code'), 'warehouse_external_mappings', ['external_code'], unique=False)
    op.create_index(op.f('ix_warehouse_external_mappings_id'), 'warehouse_external_mappings', ['id'], unique=False)
    op.create_table('dispatch_timeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dispatch_id', sa.Integer(), nullable=False),
    sa.Column('step', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('performed_by', sa.Integer(), nullable=True),
    sa.Column('performed_at', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['dispatch_id'], ['fc_dispatches.id'], ),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispatch_timeline_id'), 'dispatch_timeline', ['id'], unique=False)
    op.add_column('warehouses', sa.Column('warehouse_type', sa.Enum('CENTRAL', 'FULFILLMENT_CENTER', 'REGIONAL', 'TRANSIT', name='warehousetype'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('warehouses', 'warehouse_type')
    op.drop_index(op.f('ix_dispatch_timeline_id'), table_name='dispatch_timeline')
    op.drop_table('dispatch_timeline')
    op.drop_index(op.f('ix_warehouse_external_mappings_id'), table_name='warehouse_external_mappings')
    op.drop_index(op.f('ix_warehouse_external_mappings_external_code'), table_name='warehouse_external_mappings')
    op.drop_table('warehouse_external_mappings')
    # ### end Alembic commands ###
