"""Add dispatch_type to FCDispatch and Inventory mutation validations

Revision ID: 8f88e9788c07
Revises: f65c658e05ee
Create Date: 2026-08-07 11:26:09.657515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f88e9788c07'
down_revision: Union[str, Sequence[str], None] = 'f65c658e05ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fc_dispatches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dispatch_type', sa.String(), server_default='STANDARD', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fc_dispatches', schema=None) as batch_op:
        batch_op.drop_column('dispatch_type')

    # ### end Alembic commands ###
