"""add_warehouse_ids_to_stock_transfer

Revision ID: 91c96a4deca8
Revises: b60a5a5c8850
Create Date: 2026-08-19 13:08:50.691220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91c96a4deca8'
down_revision: Union[str, Sequence[str], None] = 'b60a5a5c8850'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_transfers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_warehouse_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('destination_warehouse_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_st_src_wh', 'warehouses', ['source_warehouse_id'], ['id'])
        batch_op.create_foreign_key('fk_st_dst_wh', 'warehouses', ['destination_warehouse_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_transfers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('destination_warehouse_id')
        batch_op.drop_column('source_warehouse_id')

    # ### end Alembic commands ###
