"""Add checksum and versioning to acc batches

Revision ID: a18c05a1dd3a
Revises: 851f2e1b41aa
Create Date: 2026-08-01 15:36:38.870271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a18c05a1dd3a'
down_revision: Union[str, Sequence[str], None] = '851f2e1b41aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acc_export_batches', sa.Column('checksum_sha256', sa.String(), nullable=True))
    op.add_column('acc_export_batches', sa.Column('template_version', sa.String(), nullable=True))
    op.add_column('acc_export_batches', sa.Column('erp_version', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_company_bill_number', 'sales', type_='unique')
    op.alter_column('inventory', 'available_qty',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('inventory', 'reserved_qty',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('inventory', 'current_qty',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('uix_user_company', 'company_users', type_='unique')
    op.drop_column('acc_export_batches', 'erp_version')
    op.drop_column('acc_export_batches', 'template_version')
    op.drop_column('acc_export_batches', 'checksum_sha256')
    # ### end Alembic commands ###
