"""Phase 6 Sales Returns and Delivery Challans

Revision ID: ae46db416b1b
Revises: e997fd815849
Create Date: 2026-08-03 12:55:08.937754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae46db416b1b'
down_revision: Union[str, Sequence[str], None] = 'e997fd815849'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_challans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challan_number', sa.String(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('challan_date', sa.DateTime(), nullable=True),
    sa.Column('seller_snapshot', sa.JSON(), nullable=True),
    sa.Column('buyer_snapshot', sa.JSON(), nullable=True),
    sa.Column('shipping_snapshot', sa.JSON(), nullable=True),
    sa.Column('vehicle_number', sa.String(), nullable=True),
    sa.Column('transport_mode', sa.String(), nullable=True),
    sa.Column('eway_bill', sa.String(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('print_count', sa.Integer(), nullable=True),
    sa.Column('last_printed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_challans_challan_number'), 'delivery_challans', ['challan_number'], unique=True)
    op.create_index(op.f('ix_delivery_challans_id'), 'delivery_challans', ['id'], unique=False)
    op.create_table('sales_returns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('return_number', sa.String(), nullable=False),
    sa.Column('return_type', sa.String(), nullable=True),
    sa.Column('return_date', sa.DateTime(), nullable=True),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('total_taxable_amount', sa.Float(), nullable=True),
    sa.Column('total_tax', sa.Float(), nullable=True),
    sa.Column('grand_total', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_returns_id'), 'sales_returns', ['id'], unique=False)
    op.create_index(op.f('ix_sales_returns_return_number'), 'sales_returns', ['return_number'], unique=True)
    op.create_table('delivery_challan_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challan_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('sku_snapshot', sa.String(), nullable=True),
    sa.Column('product_name_snapshot', sa.String(), nullable=True),
    sa.Column('hsn_snapshot', sa.String(), nullable=True),
    sa.Column('unit_snapshot', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('tax_rate', sa.Float(), nullable=True),
    sa.Column('tax_amount', sa.Float(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['challan_id'], ['delivery_challans.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_challan_items_id'), 'delivery_challan_items', ['id'], unique=False)
    op.create_table('sales_return_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('return_id', sa.Integer(), nullable=False),
    sa.Column('sale_item_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('sku_snapshot', sa.String(), nullable=True),
    sa.Column('product_name_snapshot', sa.String(), nullable=True),
    sa.Column('hsn_snapshot', sa.String(), nullable=True),
    sa.Column('unit_snapshot', sa.String(), nullable=True),
    sa.Column('returned_quantity', sa.Integer(), nullable=True),
    sa.Column('return_reason', sa.String(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('tax_rate', sa.Float(), nullable=True),
    sa.Column('tax_amount', sa.Float(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['return_id'], ['sales_returns.id'], ),
    sa.ForeignKeyConstraint(['sale_item_id'], ['sale_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_return_items_id'), 'sales_return_items', ['id'], unique=False)
    op.add_column('company_settings', sa.Column('smtp_settings', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.drop_column('company_settings', 'smtp_settings')
    op.drop_index(op.f('ix_sales_return_items_id'), table_name='sales_return_items')
    op.drop_table('sales_return_items')
    op.drop_index(op.f('ix_delivery_challan_items_id'), table_name='delivery_challan_items')
    op.drop_table('delivery_challan_items')
    op.drop_index(op.f('ix_sales_returns_return_number'), table_name='sales_returns')
    op.drop_index(op.f('ix_sales_returns_id'), table_name='sales_returns')
    op.drop_table('sales_returns')
    op.drop_index(op.f('ix_delivery_challans_id'), table_name='delivery_challans')
    op.drop_index(op.f('ix_delivery_challans_challan_number'), table_name='delivery_challans')
    op.drop_table('delivery_challans')
    # ### end Alembic commands ###
