"""Add DocumentSequence, generic voucher mapping

Revision ID: b56b61357c83
Revises: e8121eb5a6c6
Create Date: 2026-08-07 10:57:51.467949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b56b61357c83'
down_revision: Union[str, Sequence[str], None] = 'e8121eb5a6c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip dropping indices as they might not exist
    # Skip dropping invoice_sequences and service_sequences as they might not exist
    
    with op.batch_alter_table('acc_configurations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voucher_mappings', sa.JSON(), nullable=True))
        # Ignore drop column for types that weren't successfully created
        try:
            batch_op.drop_column('journal_voucher_type')
            batch_op.drop_column('debit_note_voucher_type')
            batch_op.drop_column('sales_voucher_type')
            batch_op.drop_column('purchase_voucher_type')
            batch_op.drop_column('credit_note_voucher_type')
            batch_op.drop_column('service_voucher_type')
        except:
            pass

    with op.batch_alter_table('acc_export_batches', schema=None) as batch_op:
        batch_op.drop_column('voucher_type')

    with op.batch_alter_table('company_users', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_user_company', ['user_id', 'company_id'])

    with op.batch_alter_table('document_sequences', schema=None) as batch_op:
        batch_op.alter_column('document_type',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('SALE', 'DISPATCH', 'CHALLAN', 'RETURN', 'DAMAGE', 'SERVICE', 'BATCH', 'TRANSFER', name='documenttypeenum'),
               existing_nullable=False)
        batch_op.alter_column('prefix',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('last_number',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('uq_doc_seq_comp_type_fy_prefix'), type_='unique')
        batch_op.create_unique_constraint('uix_company_doctype_fy_sequence', ['company_id', 'document_type', 'fiscal_year'])

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.alter_column('current_qty',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('reserved_qty',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('available_qty',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_company_bill_number', ['company_id', 'bill_number'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_constraint('uix_company_bill_number', type_='unique')

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.alter_column('available_qty',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('reserved_qty',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('current_qty',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('document_sequences', schema=None) as batch_op:
        batch_op.drop_constraint('uix_company_doctype_fy_sequence', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_doc_seq_comp_type_fy_prefix'), ['company_id', 'document_type', 'fiscal_year', 'prefix'])
        batch_op.alter_column('last_number',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('prefix',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('document_type',
               existing_type=sa.Enum('SALE', 'DISPATCH', 'CHALLAN', 'RETURN', 'DAMAGE', 'SERVICE', 'BATCH', 'TRANSFER', name='documenttypeenum'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)

    with op.batch_alter_table('company_users', schema=None) as batch_op:
        batch_op.drop_constraint('uix_user_company', type_='unique')

    with op.batch_alter_table('acc_export_batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voucher_type', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('acc_configurations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_voucher_type', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('credit_note_voucher_type', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('purchase_voucher_type', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('sales_voucher_type', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('debit_note_voucher_type', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('journal_voucher_type', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('voucher_mappings')

    pass

    # ### end Alembic commands ###
