"""Add idempotency_key to StockTransfer and SalesReturn

Revision ID: b60a5a5c8850
Revises: 0a0c9f0357f9
Create Date: 2026-08-17 13:38:07.809046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b60a5a5c8850'
down_revision: Union[str, Sequence[str], None] = '0a0c9f0357f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_returns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idempotency_key', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_sales_returns_idempotency_key'), ['idempotency_key'], unique=False)
        batch_op.create_unique_constraint('uix_company_salesreturn_idempotency_key', ['company_id', 'idempotency_key'])

    with op.batch_alter_table('stock_transfers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idempotency_key', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_stock_transfers_idempotency_key'), ['idempotency_key'], unique=False)
        batch_op.create_unique_constraint('uix_from_company_transfer_idempotency_key', ['from_company_id', 'idempotency_key'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_transfers', schema=None) as batch_op:
        batch_op.drop_constraint('uix_from_company_transfer_idempotency_key', type_='unique')
        batch_op.drop_index(batch_op.f('ix_stock_transfers_idempotency_key'))
        batch_op.drop_column('idempotency_key')

    with op.batch_alter_table('sales_returns', schema=None) as batch_op:
        batch_op.drop_constraint('uix_company_salesreturn_idempotency_key', type_='unique')
        batch_op.drop_index(batch_op.f('ix_sales_returns_idempotency_key'))
        batch_op.drop_column('idempotency_key')

    # ### end Alembic commands ###
