"""Add state hubs and warehouse augmentations

Revision ID: c885d437bcc9
Revises: ae46db416b1b
Create Date: 2026-08-03 16:40:01.048494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c885d437bcc9'
down_revision: Union[str, Sequence[str], None] = 'ae46db416b1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('state_hubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('hub_code', sa.String(), nullable=False),
    sa.Column('hub_name', sa.String(), nullable=False),
    sa.Column('gstin', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('state_code', sa.String(), nullable=True),
    sa.Column('contact_person', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'hub_code', name='uix_company_hub_code')
    )
    op.create_index(op.f('ix_state_hubs_hub_code'), 'state_hubs', ['hub_code'], unique=False)
    op.create_index(op.f('ix_state_hubs_id'), 'state_hubs', ['id'], unique=False)
    op.create_table('warehouse_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'user_id', name='uix_warehouse_user')
    )
    op.create_index(op.f('ix_warehouse_users_id'), 'warehouse_users', ['id'], unique=False)
    
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hub_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('manager', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_warehouse_hub', 'state_hubs', ['hub_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_warehouse_hub', type_='foreignkey')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('manager')
        batch_op.drop_column('hub_id')
    op.drop_index(op.f('ix_warehouse_users_id'), table_name='warehouse_users')
    op.drop_table('warehouse_users')
    op.drop_index(op.f('ix_state_hubs_id'), table_name='state_hubs')
    op.drop_index(op.f('ix_state_hubs_hub_code'), table_name='state_hubs')
    op.drop_table('state_hubs')
    # ### end Alembic commands ###
