"""Add POS Schema

Revision ID: cba99dc7c9e1
Revises: 7638c0224e8a
Create Date: 2026-07-28 14:19:14.797794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cba99dc7c9e1'
down_revision: Union[str, Sequence[str], None] = '7638c0224e8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('tax_mode', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('gstin', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_companies_id'), ['id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)

    op.create_table('company_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_users_id'), ['id'], unique=False)

    op.create_table('pos_sequences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('last_sequence', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'date', name='uix_company_pos_date')
    )
    with op.batch_alter_table('pos_sequences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pos_sequences_id'), ['id'], unique=False)

    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_number', sa.String(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('customer_phone', sa.String(), nullable=True),
    sa.Column('customer_gstin', sa.String(), nullable=True),
    sa.Column('sale_date', sa.DateTime(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('discount_type', sa.String(), nullable=True),
    sa.Column('total_taxable_amount', sa.Float(), nullable=True),
    sa.Column('total_tax', sa.Float(), nullable=True),
    sa.Column('grand_total', sa.Float(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'bill_number', name='uix_company_bill_number')
    )
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_bill_number'), ['bill_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_id'), ['id'], unique=False)

    op.create_table('sale_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('hsn', sa.String(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('gst_rate', sa.Float(), nullable=True),
    sa.Column('taxable_amount', sa.Float(), nullable=True),
    sa.Column('cgst', sa.Float(), nullable=True),
    sa.Column('sgst', sa.Float(), nullable=True),
    sa.Column('igst', sa.Float(), nullable=True),
    sa.Column('uom', sa.String(), nullable=True),
    sa.Column('line_total', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_items_id'), ['id'], unique=False)

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_company_id', 'companies', ['company_id'], ['id'])

    with op.batch_alter_table('amazon_sync_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_index(batch_op.f('ix_amazon_sync_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_amazon_sync_logs_order_id'), ['order_id'], unique=False)
        batch_op.create_unique_constraint('uix_company_order_id', ['company_id', 'order_id'])
        batch_op.create_foreign_key('fk_company_id', 'companies', ['company_id'], ['id'])

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_inventory_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_warehouse_id'), ['warehouse_id'], unique=False)
        batch_op.create_unique_constraint('uix_company_prod_wh', ['company_id', 'product_id', 'warehouse_id'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_company_id', 'companies', ['company_id'], ['id'])
        batch_op.create_foreign_key('fk_company_id', 'products', ['product_id'], ['id'])
        batch_op.drop_column('product_sku')

    with op.batch_alter_table('inventory_movements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_company_id', 'companies', ['company_id'], ['id'])
        batch_op.create_foreign_key('fk_company_id', 'products', ['product_id'], ['id'])
        batch_op.drop_column('product_sku')

    with op.batch_alter_table('inventory_snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_company_id', 'companies', ['company_id'], ['id'])
        batch_op.create_foreign_key('fk_company_id', 'products', ['product_id'], ['id'])
        batch_op.drop_column('product_sku')

    with op.batch_alter_table('job_execution_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_company_id', 'companies', ['company_id'], ['id'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('hsn_code', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('default_gst_rate', sa.Float(), nullable=True))
        batch_op.create_index(batch_op.f('ix_products_id'), ['id'], unique=False)
        batch_op.create_unique_constraint('uix_company_sku', ['company_id', 'sku'])
        batch_op.create_foreign_key('fk_company_id', 'companies', ['company_id'], ['id'])

    with op.batch_alter_table('reports_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_company_id', 'companies', ['company_id'], ['id'])

    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_warehouses_code'))
        batch_op.create_index(batch_op.f('ix_warehouses_code'), ['code'], unique=False)
        batch_op.create_unique_constraint('uix_company_warehouse_code', ['company_id', 'code'])
        batch_op.create_foreign_key('fk_company_id', 'companies', ['company_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uix_company_warehouse_code', type_='unique')
        batch_op.drop_index(batch_op.f('ix_warehouses_code'))
        batch_op.create_index(batch_op.f('ix_warehouses_code'), ['code'], unique=1)
        batch_op.drop_column('company_id')

    with op.batch_alter_table('reports_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uix_company_sku', type_='unique')
        batch_op.drop_index(batch_op.f('ix_products_id'))
        batch_op.drop_column('default_gst_rate')
        batch_op.drop_column('hsn_code')
        batch_op.drop_column('company_id')
        batch_op.drop_column('id')

    with op.batch_alter_table('job_execution_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('inventory_snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_sku', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_company_id', 'products', ['product_sku'], ['sku'])
        batch_op.drop_column('product_id')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('inventory_movements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_sku', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_company_id', 'products', ['product_sku'], ['sku'])
        batch_op.drop_column('product_id')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_sku', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_company_id', 'products', ['product_sku'], ['sku'])
        batch_op.drop_constraint('uix_company_prod_wh', type_='unique')
        batch_op.drop_index(batch_op.f('ix_inventory_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_product_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_company_id'))
        batch_op.drop_column('product_id')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('amazon_sync_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uix_company_order_id', type_='unique')
        batch_op.drop_index(batch_op.f('ix_amazon_sync_logs_order_id'))
        batch_op.drop_index(batch_op.f('ix_amazon_sync_logs_id'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('company_id')

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_items_id'))

    op.drop_table('sale_items')
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_id'))
        batch_op.drop_index(batch_op.f('ix_sales_bill_number'))

    op.drop_table('sales')
    with op.batch_alter_table('pos_sequences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pos_sequences_id'))

    op.drop_table('pos_sequences')
    with op.batch_alter_table('company_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_users_id'))

    op.drop_table('company_users')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_id'))
        batch_op.drop_index(batch_op.f('ix_companies_code'))

    op.drop_table('companies')
    # ### end Alembic commands ###
