"""Add execution idempotency key

Revision ID: d893ec7e3ff0
Revises: 377c1d491021
Create Date: 2026-08-20 13:33:49.717641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd893ec7e3ff0'
down_revision: Union[str, Sequence[str], None] = '377c1d491021'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_approval_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('execution_idempotency_key', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_admin_approval_requests_execution_idempotency_key'), ['execution_idempotency_key'], unique=True)

    with op.batch_alter_table('fc_dispatches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('execution_idempotency_key', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_fc_dispatches_execution_idempotency_key'), ['execution_idempotency_key'], unique=True)

    with op.batch_alter_table('fc_returns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('execution_idempotency_key', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_fc_returns_execution_idempotency_key'), ['execution_idempotency_key'], unique=True)

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('execution_idempotency_key', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_sales_execution_idempotency_key'), ['execution_idempotency_key'], unique=True)

    with op.batch_alter_table('sales_returns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('execution_idempotency_key', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_sales_returns_execution_idempotency_key'), ['execution_idempotency_key'], unique=True)

    with op.batch_alter_table('stock_transfers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('execution_idempotency_key', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_stock_transfers_execution_idempotency_key'), ['execution_idempotency_key'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_transfers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_transfers_execution_idempotency_key'))
        batch_op.drop_column('execution_idempotency_key')

    with op.batch_alter_table('sales_returns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_returns_execution_idempotency_key'))
        batch_op.drop_column('execution_idempotency_key')

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_execution_idempotency_key'))
        batch_op.drop_column('execution_idempotency_key')

    with op.batch_alter_table('fc_returns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fc_returns_execution_idempotency_key'))
        batch_op.drop_column('execution_idempotency_key')

    with op.batch_alter_table('fc_dispatches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fc_dispatches_execution_idempotency_key'))
        batch_op.drop_column('execution_idempotency_key')

    with op.batch_alter_table('admin_approval_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_approval_requests_execution_idempotency_key'))
        batch_op.drop_column('execution_idempotency_key')

    # ### end Alembic commands ###
