"""Add DocumentSequence and update AccountingConfig

Revision ID: e1c99e458698
Revises: e8121eb5a6c6
Create Date: 2026-08-06 21:15:12.796332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1c99e458698'
down_revision: Union[str, Sequence[str], None] = 'e8121eb5a6c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acc_configurations', sa.Column('sales_voucher_type', sa.String(), nullable=True))
    op.add_column('acc_configurations', sa.Column('purchase_voucher_type', sa.String(), nullable=True))
    op.add_column('acc_configurations', sa.Column('credit_note_voucher_type', sa.String(), nullable=True))
    op.add_column('acc_configurations', sa.Column('debit_note_voucher_type', sa.String(), nullable=True))
    op.add_column('acc_configurations', sa.Column('journal_voucher_type', sa.String(), nullable=True))
    op.add_column('acc_configurations', sa.Column('service_voucher_type', sa.String(), nullable=True))
    op.drop_column('acc_configurations', 'default_voucher_type')
    op.add_column('acc_export_batches', sa.Column('success_count', sa.Integer(), nullable=True))
    op.add_column('acc_export_batches', sa.Column('failed_count', sa.Integer(), nullable=True))
    op.add_column('acc_export_batches', sa.Column('voucher_type', sa.String(), nullable=True))
    op.create_unique_constraint('uix_user_company', 'company_users', ['user_id', 'company_id'])
    op.alter_column('inventory', 'current_qty',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('inventory', 'reserved_qty',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('inventory', 'available_qty',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint('uix_company_bill_number', 'sales', ['company_id', 'bill_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_company_bill_number', 'sales', type_='unique')
    op.alter_column('inventory', 'available_qty',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('inventory', 'reserved_qty',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('inventory', 'current_qty',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('uix_user_company', 'company_users', type_='unique')
    op.drop_column('acc_export_batches', 'voucher_type')
    op.drop_column('acc_export_batches', 'failed_count')
    op.drop_column('acc_export_batches', 'success_count')
    op.add_column('acc_configurations', sa.Column('default_voucher_type', sa.VARCHAR(), nullable=True))
    op.drop_column('acc_configurations', 'service_voucher_type')
    op.drop_column('acc_configurations', 'journal_voucher_type')
    op.drop_column('acc_configurations', 'debit_note_voucher_type')
    op.drop_column('acc_configurations', 'credit_note_voucher_type')
    op.drop_column('acc_configurations', 'purchase_voucher_type')
    op.drop_column('acc_configurations', 'sales_voucher_type')
    # ### end Alembic commands ###
