"""add is_verified to job_cards

Revision ID: e5ffc85b7f0d
Revises: 868ed8b3da70
Create Date: 2026-08-11 00:28:26.728052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5ffc85b7f0d'
down_revision: Union[str, Sequence[str], None] = '868ed8b3da70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_sequences', schema=None) as batch_op:
        batch_op.alter_column('document_type',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('SALE', 'DISPATCH', 'CHALLAN', 'RETURN', 'DAMAGE', 'SERVICE', 'BATCH', 'TRANSFER', 'JOB_CARD', 'SERVICE_INVOICE', name='documenttypeenum'),
               existing_nullable=False)

    with op.batch_alter_table('job_cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_cards', schema=None) as batch_op:
        batch_op.drop_column('is_verified')

    with op.batch_alter_table('document_sequences', schema=None) as batch_op:
        batch_op.alter_column('document_type',
               existing_type=sa.Enum('SALE', 'DISPATCH', 'CHALLAN', 'RETURN', 'DAMAGE', 'SERVICE', 'BATCH', 'TRANSFER', 'JOB_CARD', 'SERVICE_INVOICE', name='documenttypeenum'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)

    # ### end Alembic commands ###
