"""add_source_warehouse_id_and_transaction_origin

Revision ID: e8121eb5a6c6
Revises: 8c70a71d0517
Create Date: 2026-08-05 11:19:12.874748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8121eb5a6c6'
down_revision: Union[str, Sequence[str], None] = '8c70a71d0517'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_settings', sa.Column('export_internal_distribution_to_accounting', sa.Boolean(), nullable=True))
    with op.batch_alter_table('fc_dispatches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_warehouse_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_fc_dispatch_source_warehouse', 'warehouses', ['source_warehouse_id'], ['id'])
    op.add_column('sales', sa.Column('transaction_origin', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'transaction_origin')
    with op.batch_alter_table('fc_dispatches', schema=None) as batch_op:
        batch_op.drop_constraint('fk_fc_dispatch_source_warehouse', type_='foreignkey')
        batch_op.drop_column('source_warehouse_id')
    op.drop_column('company_settings', 'export_internal_distribution_to_accounting')
    # ### end Alembic commands ###
