"""Add DefectiveInventory and inspection_images

Revision ID: e997fd815849
Revises: 7497b42f0300
Create Date: 2026-08-03 11:34:14.790415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e997fd815849'
down_revision: Union[str, Sequence[str], None] = '7497b42f0300'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('defective_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('amazon_return_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sku_snapshot', sa.String(), nullable=False),
    sa.Column('product_name_snapshot', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('return_reason', sa.String(), nullable=True),
    sa.Column('inspection_notes', sa.Text(), nullable=True),
    sa.Column('inspection_images', sa.JSON(), nullable=True),
    sa.Column('inspector_id', sa.Integer(), nullable=True),
    sa.Column('inspection_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['amazon_return_id'], ['amazon_returns.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_defective_inventory_id'), 'defective_inventory', ['id'], unique=False)
    op.create_index(op.f('ix_defective_inventory_sku_snapshot'), 'defective_inventory', ['sku_snapshot'], unique=False)
    op.add_column('amazon_returns', sa.Column('inspection_images', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('amazon_returns', 'inspection_images')
    op.drop_index(op.f('ix_defective_inventory_sku_snapshot'), table_name='defective_inventory')
    op.drop_index(op.f('ix_defective_inventory_id'), table_name='defective_inventory')
    op.drop_table('defective_inventory')
    # ### end Alembic commands ###
