"""Add batch_number to export batch

Revision ID: f65c658e05ee
Revises: 76feb95df8f1
Create Date: 2026-08-07 11:03:18.746076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f65c658e05ee'
down_revision: Union[str, Sequence[str], None] = '76feb95df8f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('acc_export_batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch_number', sa.String(), nullable=True))
        batch_op.create_unique_constraint('uq_acc_export_batches_batch_number', ['batch_number'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('acc_export_batches', schema=None) as batch_op:
        batch_op.drop_constraint('uq_acc_export_batches_batch_number', type_='unique')
        batch_op.drop_column('batch_number')

    # ### end Alembic commands ###
