"""Add FC Dispatch and Return Models

Revision ID: fa2858e8617f
Revises: c885d437bcc9
Create Date: 2026-08-04 12:35:14.110735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa2858e8617f'
down_revision: Union[str, Sequence[str], None] = 'c885d437bcc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('damage_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('claim_number', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('video_reference', sa.String(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('claim_status', sa.String(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_damage_claims_claim_number'), 'damage_claims', ['claim_number'], unique=True)
    op.create_index(op.f('ix_damage_claims_id'), 'damage_claims', ['id'], unique=False)
    op.create_table('fc_dispatches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('delivery_challan_id', sa.Integer(), nullable=True),
    sa.Column('dispatch_number', sa.String(), nullable=False),
    sa.Column('dispatch_status', sa.String(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['delivery_challan_id'], ['delivery_challans.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['sales.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fc_dispatches_dispatch_number'), 'fc_dispatches', ['dispatch_number'], unique=True)
    op.create_index(op.f('ix_fc_dispatches_id'), 'fc_dispatches', ['id'], unique=False)
    op.create_table('fc_dispatch_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dispatch_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sku_snapshot', sa.String(), nullable=True),
    sa.Column('product_name_snapshot', sa.String(), nullable=True),
    sa.Column('hsn_snapshot', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('gst_rate', sa.Float(), nullable=False),
    sa.Column('taxable_amount', sa.Float(), nullable=False),
    sa.Column('tax_amount', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['dispatch_id'], ['fc_dispatches.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fc_dispatch_items_id'), 'fc_dispatch_items', ['id'], unique=False)
    op.create_table('fc_returns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('dispatch_id', sa.Integer(), nullable=True),
    sa.Column('return_number', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dispatch_id'], ['fc_dispatches.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fc_returns_id'), 'fc_returns', ['id'], unique=False)
    op.create_index(op.f('ix_fc_returns_return_number'), 'fc_returns', ['return_number'], unique=True)
    op.create_table('fc_return_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fc_return_id', sa.Integer(), nullable=False),
    sa.Column('dispatch_item_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('return_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dispatch_item_id'], ['fc_dispatch_items.id'], ),
    sa.ForeignKeyConstraint(['fc_return_id'], ['fc_returns.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fc_return_items_id'), 'fc_return_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fc_return_items_id'), table_name='fc_return_items')
    op.drop_table('fc_return_items')
    op.drop_index(op.f('ix_fc_returns_return_number'), table_name='fc_returns')
    op.drop_index(op.f('ix_fc_returns_id'), table_name='fc_returns')
    op.drop_table('fc_returns')
    op.drop_index(op.f('ix_fc_dispatch_items_id'), table_name='fc_dispatch_items')
    op.drop_table('fc_dispatch_items')
    op.drop_index(op.f('ix_fc_dispatches_id'), table_name='fc_dispatches')
    op.drop_index(op.f('ix_fc_dispatches_dispatch_number'), table_name='fc_dispatches')
    op.drop_table('fc_dispatches')
    op.drop_index(op.f('ix_damage_claims_id'), table_name='damage_claims')
    op.drop_index(op.f('ix_damage_claims_claim_number'), table_name='damage_claims')
    op.drop_table('damage_claims')
    # ### end Alembic commands ###
