"""Add batch_subtype to AccountingExportBatch

Revision ID: fbc3ad4bccce
Revises: fa2858e8617f
Create Date: 2026-08-04 16:50:56.335733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbc3ad4bccce'
down_revision: Union[str, Sequence[str], None] = 'fa2858e8617f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('acc_export_batches', sa.Column('batch_subtype', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('acc_export_batches', 'batch_subtype')
    # ### end Alembic commands ###
